AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: go1.x
    Handler: api
    Environment:
      Variables:
        TABLE_NAME: !Ref EntryTable

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        DefaultAuthorizer: ApiKeyAuthorizer
        Authorizers:
          ApiKeyAuthorizer:
            FunctionArn: !GetAtt ApiKeyAuthFunction.Arn
            Identity:
              Header: x-api-key
  Root:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EntryTable
      Events:
        RootHandler:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: '/{key}'
            Method: get
            Auth:
              ApiKeyRequired: false
              Authorizer: 'NONE'

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EntryTable
      Events:
        CreateLink:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: '/api/v1/links'
            Method: post

  ApiKeyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: auth
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - apigateway:GET
              Resource:
                - arn:aws:apigateway:us-east-1::/apikeys

  EntryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: entry_key
          AttributeType: S
      KeySchema:
        - AttributeName: entry_key
          KeyType: HASH
